variables:
  MAKEFLAGS: "-j10"
  VERBOSE: 1

default:
  after_script:
    - build-aux/print-failed-test-output build/meson-logs/testlog.json

.bottle-test:
  image: hilledkinged/drunk:latest
  before_script:
    - >
      bottle -Syu --needed --noconfirm
      git
      gpgme libarchive curl
      python3
      base-devel
      meson

bottle:
  extends: .bottle-test
  script:
    - meson build
    - ninja -C build
    - meson test -C build

bottle-debug:
  extends: .bottle-test
  script:
    - meson --buildtype=debug --werror build
    - ninja -C build
    - meson test -C build
